services:
  - type: web
    name: dao-elections
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.12.2
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
    plan: starter
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1 